### ISSUE TITLE
Extension Object table questions

### ISSUE THREAD

**Issue by GreatScott000** [TKapitan/ALRM-VSCode#25]
Looking at the extension object table.  When I use Synchronize, the "Extension ID" field is always an 'empty' GUID ({00000000-0000-0000-0000-000000000000}) and the 'Extends Object Name' field for page/table extensions (I don't have any other types of extension in the apps right now) is also empty.

Is this intentional?

**Comment by TKapitan** [comment]
Before you can use the Synchronize command, you have to use Initialize first (it shouldn't be possible to run Synchronize if the extension hasn't been initialized first - you should get an error message like "You have to initialize the project"). During the initialization (when the extension is created in BC) the app ID (GUI from app.json) is used as the primary key in BC.

Extends object name shouldn't be empty, do you have the last version of VS Code extension from the marketplace. We use this solution in our company with 25 developers and it works well...

**Comment by GreatScott000** [comment]
I am setting it up again and will see.  I am using version 0.4.3 of the VS Code extension.  Which shows as the current version.

**Comment by GreatScott000** [comment]
Removed the extension (and data) from the database and republished it (via VS Code as it was easiest).  Setup the Assignable Ranges.  In VS Code I set the api URL and company ID.  Initialized the app, then synchronized app.  Still no extension ID or Extends objects values in the C4BC Extension Object (80003) table.

![image](https://user-images.githubusercontent.com/4333956/126176034-1dbb9969-b6a6-46da-9734-0140209b6bca.png)

**Comment by TKapitan** [comment]
Thanks, I have two ideas

1) No ID - the parser for app.json is case-sensitive and looks for the 'id' value. Maybe that's the problem, I'll update app.json parsing in the next version.

2) Which API version are you using? Go to VS Code Setup -> Preferences -> ALRM API Version. Extended object name synchronization is supported since v1.1. You can also force all clients to use this API version in your BC in "ALRM Setup" using "Minimal API Version".

**Comment by GreatScott000** [comment]
My app.json looks like this:
![image](https://user-images.githubusercontent.com/4333956/126619958-27e98623-51d9-4203-9b5e-98af155b2d94.png)

Changing the API version in VS Code Settings has resolved the issue with "Extends Object Name" not being set.

![image](https://user-images.githubusercontent.com/4333956/126620172-337688af-a8e1-4dd1-9d0e-ef5ea174c2f8.png)

**Comment by TKapitan** [comment]
I am out of ideas  :/ 
Are you able to verify whether the BC API is called without this parameter or whether the ID is lost somewhere in BC? The extensions are in use by three different companies by more than 50 users, and I haven't seen this problem anywhere else...

The API page is 80013 "C4BC Extension API v1.1", and the extension is initialized using Create API method...

Based on my knowledge, it shouldn't be possible to initialize without an ID (in VS Code, there is an error when the ID in app.json is not found).
`
    const app: App = App.fromJson(require(appJsonFileName));
    if (app === null || app.id === '') {
        throw new Error('App.json is not valid!');
    }
`

The extension ID is the field using which VS Code finds the extension in BC - that means that whenever you call sync, the new extension is initialized in BC? Because the system can not find the extension using the app.json ID?

**Comment by GreatScott000** [comment]
If I try to init the extension again I get this so it is not recreating an extension record.
![image](https://user-images.githubusercontent.com/4333956/126749596-0a714188-0aab-4042-b8c7-342c29395459.png)
Syncing the extension shows that it finds the same extension number so again it is finding the existing record.
![image](https://user-images.githubusercontent.com/4333956/126749723-242daa51-e518-43aa-8bf4-d7903cf7b8a1.png)
The ID is filled in on the Extension Header table
![image](https://user-images.githubusercontent.com/4333956/126749791-08fe6329-8118-4161-af64-0e2dcf60cf87.png)
But not on the Extension Object table
![image](https://user-images.githubusercontent.com/4333956/126749823-5931f43e-3588-4b4f-85f4-8725fc5d73eb.png)
Looking at the code, for ALRM, the Extension ID in the Extension Object table is never referenced so the API is not filling it.
![image](https://user-images.githubusercontent.com/4333956/126749997-b608ed65-c981-40f6-8c9e-31e5cb065925.png)

So my question is, has the Extension ID field in the Extension Object table been overlooked or just left over from a previous design concept?

**Comment by TKapitan** [comment]
Thanks for the analysis! 

What can I see from the Git notes, the field was created by one of my colleagues during the hackathon when the extension was created. So it's probably a relic that is no longer used by any process but I will fix it with the next release...

![image](https://user-images.githubusercontent.com/37966300/126754264-a1636058-c6cb-445f-933b-167f87bc5eaa.png)
