### ISSUE TITLE
Snippets to trigger the ALRM commands?

### ISSUE THREAD

**Issue by deerware** [TKapitan/ALRM-VSCode#6]
It would be nice to have snippets available. For example `trmfield`. The snippet could generate the same code block as the command does now.
It would even simplify the creation of new objects. Just create a new file manually in the right place and then use a snippet like `trmtableext`. Again the same code block would suffice, only problem would be registering the object's name, but the snippet could maybe trigger the same input box as the command does.

**Comment by TKapitan** [comment]
Unfortunately, based on what I found in the docu, it is impossible to trigger commands using snippet functionality. 

I found the only workaround to bind some of the commands (new object, new object line, for example) to a specific key combination. I can also add a new command that will insert an object with the name and id generated through API to the existing file instead of creating a new file (so it will be similar to the new object line command).
